project:
  type: website
  output-dir: docs

website:
  title: "Global Food Prices and Expenditure Patterns"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/ETC5523-2024/assignment-3-v2-creating-a-blog-PrajaktaChavan0096

format:
  html:
    theme: cosmo  # Bootstrap theme
    css: styles.css  # Link to external CSS file
    toc: true  # Enable table of contents
    toc-location: left  # Place TOC on the left for better navigation
    number-sections: true  # Number the sections for readability

# Custom theming to enhance readability and aesthetics
editor_options:
  markdown:
    wrap: 72  # Improve readability in markdown editor
    color: auto  # Use adaptive color scheme
